### ISSUE TITLE
Union type

### ISSUE THREAD

**Issue by OliverJAsh** [gcanti/fp-ts-routing#10]
Thanks for the fantastic lib!

I need to parse a route like `/search/{users,photos,collections}/:query`.

IIUC, currently the only way to define this is with 3 separate routes. However, ideally I could parse it with one, where `{users,photos,collections}` becomes a union of string literals (`"users" | "photos" | "collections"`).

Would you consider adding a union type?

**Comment by gcanti** [comment]
You can use the generic `type` combinator which accepts a io-ts runtime type

```ts
import * as t from 'io-ts'
import { lit, type, end, Route } from 'fp-ts-routing'

const T = t.keyof({
  users: null,
  photos: null,
  collections: null
})
const match = lit('search')
  .then(type('topic', T))
  .then(end)

console.log(match.parser.run(Route.parse('/search/users')))
/*
some([{
  "topic": "users"
}, {
  "parts": [],
  "query": {}
}])
*/
console.log(match.parser.run(Route.parse('/search/collections')))
/*
some([{
  "topic": "collections"
}, {
  "parts": [],
  "query": {}
}])
*/
```
