### ISSUE TITLE
Format function for all `Location`s

### ISSUE THREAD

**Issue by OliverJAsh** [gcanti/fp-ts-routing#14]
It's possible to write a function that goes from `string` to `Location`, aka `parseLocation`. Is it possible to write the reverse, i.e. a `formatAnyLocation`—a function that goes from `Location` to `string`?

Currently I'm having to match on each `Location` and map it manually to the corresponding `Match`. However, this means I'm repeating myself, because I'm already mapping `Match`s to `Location`s in my router.

**Comment by gcanti** [comment]
In general is not possible, I guess it really depends on how `Location` is defined. 

For example (using the example in the readme) `NotFound` is a `Location` but there's no corresponding formatter
