### ISSUE TITLE
Option to disable URI encoding/decoding

### ISSUE THREAD

**Issue by OliverJAsh** [gcanti/fp-ts-routing#18]
I have a path part which I deliberately don't want to URI encode/decode. How would you suggest achieving this?

For reference, the URL is `/@${username}`, e.g. `/@oliverjash` (https://unsplash.com/@oliverjash). `@` would be URI encoded to `%40` which is not desirable.

**Comment by gcanti** [comment]
From https://github.com/gcanti/fp-ts-routing/pull/19

> Should we just remove the in-built encoding/decoding, and let the user handle it where it's necessary?

We could keep the in-built encoding/decoding, the user can define its own encoder when necessary

```ts
const search = lit('search')
  .then(str('query'))
  .then(end)

const raw = search.formatter.run(Route.empty, { query: 'foo & bar' })

console.log(raw)
// => Route { parts: [ 'search', 'foo & bar' ], query: {} }

// define you own encoder
declare function myencoding(raw: Route): string

const path = myencoding(raw)
```

**Comment by OliverJAsh** [comment]
What are the example described at the top of this issue? We don't want @ to be encoded (in this specific example). The only way I can see of achieving that is disabling or removing the inbuilt encoding

**Comment by gcanti** [comment]
I don't know how to achieve what you want, we need a proposal. However isn't disabling or removing the in-built encoding equivalent to simply get the raw data structure as I did in the example above? Then, in those specific cases, you could define your own encoder.

**Comment by OliverJAsh** [comment]
Hmm, I see what you're saying now.

The issue with that is if I want different encoding for each path part, my custom encoding function would have to rely on the index of the parts array. E.g. if I only want to URI encode the `:query` part of `/search/:query`.

Alternatively, if there was no in-built encoding, I could preprocess/postprocess the parts when parsing or before formatting, e.g.

``` ts
search.parser.map(({ query }) => new Search(encodeURIComponent(slugify(query))));

format(search.formatter, { query: decodeURIComponent(deslugify(query)) });
```

For the `/@${username}` example, I would simply have no encoding/decoding.

One other idea I had is that the encoding/decoding could be done as part of the io-ts type. For example, you could have something like `str` but where the undelying io-ts type enforces URI component encoding on encoding, and URI component decoding on decoding.

``` ts
import { end, lit, Match, Route, type } from "fp-ts-routing";
import * as t from "io-ts";

const URIEncodedString = new t.Type<string, string>(
  "URIEncodedString",
  (m): m is string => t.string.is(m),
  (m, c) =>
    t.string.validate(m, c).chain(s => {
      const d = decodeURIComponent(s);
      return t.success(d);
    }),
  encodeURIComponent
);

const formatLocation = <A extends object>(match: Match<A>) => (
  location: A
): string => match.formatter.run(Route.empty, location).toString();

const search = lit("search")
  .then(type("query", URIEncodedString))
  .then(end);

console.log(formatLocation(search)({ query: "foo & bar" })); // => /search/foo%20%26%20bar
```

**Comment by OliverJAsh** [comment]
Hi @gcanti, do you have any thoughts on the above?

**Comment by gcanti** [comment]
@OliverJAsh They look like good options if you can work with raw data, so

> Option to disable URI encoding/decoding

I could add an option to `Route.parse`, `Route.prototype.toString` and `format`

```ts
export class Route {
  ...
  static parse = (s: string, decode: boolean = true): Route => {
    ...
  }
  ...
  toString(encode: boolean = true): string {
    ...
  }
}

export const format = <A extends object>(formatter: Formatter<A>, a: A, encode: boolean = true): string => {
  ...
}
```

**Comment by OliverJAsh** [comment]
That would be brilliant!
