### ISSUE TITLE
Cannot run  the tests..

### ISSUE THREAD

**Issue by sledorze** [gcanti/fp-ts-routing#24]
I'm not sure how I'm supposed to run the tests..

<img width="766" alt="screen shot 2018-08-04 at 23 53 37" src="https://user-images.githubusercontent.com/416760/43680767-f6024bc0-9841-11e8-93b5-efa928c69c42.png">

**Comment by gcanti** [comment]
That failure looks similar to https://github.com/gcanti/io-ts-types/pull/48#issuecomment-410249933

**Comment by sledorze** [comment]
Works, thanks!
