### ISSUE TITLE
Expose the Routing Algebra

### ISSUE THREAD

**Issue by sledorze** [gcanti/fp-ts-routing#29]
This is a direct follow up of https://github.com/gcanti/fp-ts-routing/pull/25

It may be a useful general pattern that can be used in other libraries (eg `io-ts`).

**Comment by gcanti** [comment]
@sledorze no, such a `Routing` language is arbitrary, it could be defined as

```ts
interface Routing2<F> {
  end: MatchSyntax<F, {}>
  str: <K extends string>(k: K) => MatchSyntax<F, { [_ in K]: string }>
  int: <K extends string>(k: K) => MatchSyntax<F, { [_ in K]: number }>
  lit: (s: string) => MatchSyntax<F, {}>
  query: <A extends object>(type: t.Type<A, Query>) => MatchSyntax<F, A>
}
```

or you could even compile a subset of swagger to `Match`.

A specific `Routing` language implemented in your codebase is fine if it fits your needs, but should be external to the library.

**Comment by sledorze** [comment]
Having played a bit yesterday and today with several integration for a io-ts derived lang, I fully understand that now (had to accommodate the lang to the actual API needs rather than mimicking the API of to a particular derivation).
That was a bad and short sighted solution.
