### ISSUE TITLE
Upgrade dependencies to io-ts-types 0.4.0

### ISSUE THREAD

**Issue by sledorze** [gcanti/fp-ts-routing#30]

**Comment by gcanti** [comment]
@sledorze `fp-ts-routing` is compatible with both versions (only `NumberFromString` is imported) so we could change to

```
"io-ts-types": "^0.3.6 || ^0.4.0"
```

right?

**Comment by sledorze** [comment]
(Note: I did not know that was possible..)

**Comment by sledorze** [comment]
Thanks!
