### ISSUE TITLE
Query should accept null in addition to undefined

### ISSUE THREAD

**Issue by sledorze** [gcanti/fp-ts-routing#32]
Query type is:

```typescript
export interface Query {
  [key: string]: string | Array<string> | undefined
}
```

Which prevent usage with Types having null output.
For instance:
https://github.com/gcanti/io-ts-types/blob/master/src/fp-ts/createOptionFromNullable.ts#L20

Can we have:
```typescript
export interface Query {
  [key: string]: string | Array<string> | undefined | null
}
```

**Comment by gcanti** [comment]
LGTM

**Comment by sledorze** [comment]
@gcanti Ok I'll do it :)
