### ISSUE TITLE
fp-ts@2

### ISSUE THREAD

**Issue by mlegenhausen** [gcanti/fp-ts-routing#42]
Will this library be ported to `fp-ts@2`? I can give it a try when this library should have a future.

**Comment by gcanti** [comment]
> Will this library be ported to fp-ts@2?

Yes!

**Comment by mlegenhausen** [comment]
@gcanti I am currently working on a port I have just one problem. All your `class`es have a `extends object` constraint. How can I apply this constraint when I add the type class to `URItoKind<A>`?

Example

```
declare module 'fp-ts/lib/HKT' {
  interface URItoKind<A> {
    Parser: Parser<A>
  }
}

export const URI = 'Parser'

export type URI = typeof URI

export interface Parser<A> { // I can not set A extends object
  (r: Route): O.Option<[A, Route]>
}
```

**Comment by gcanti** [comment]
@mlegenhausen actually, as a first step, my intention was to make the current version compatible with both fp-ts@1 and fp-ts@2 without breaking changes (if possible of course)

**Comment by gcanti** [comment]
@mlegenhausen indeed looks like is possible: https://github.com/gcanti/fp-ts-routing/pull/43

**Comment by gcanti** [comment]
Released https://github.com/gcanti/fp-ts-routing/releases/tag/0.4.2

**Comment by gcanti** [comment]
https://github.com/gcanti/fp-ts-routing/releases/tag/0.5.0
