### ISSUE TITLE
Support for t.partial in the query-function.

### ISSUE THREAD

**Issue by merisbahti** [gcanti/fp-ts-routing#51]
Hey, is there any reason we cannot have both `queryPartial` and `partial`?

It would be the same, except that the `io-ts` type would allow for an encoded `Partial<Record<...>>` instead of just `Record<...>`, like this:

```typescript
export function queryPartial<A, T>(type: Type<A, Partial<Record<keyof T, QueryValues>>>): Match<A> {
  return new Match(
    new Parser(r => option.map(fromEither(type.decode(r.query)), query => tuple(query, new Route(r.parts, {})))),
    new Formatter((r, query) => new Route(r.parts, type.encode(query)))
  )
}
```

I find it way more useful, _and_ it would support required query parameters aswell. I find that when I declare routes most of the time I have atleast some optional query parameters, imagine a page where a user can have some or no filters on it - and I don't want to have multiple routes for each case.

Thanks in advance!

**Comment by gcanti** [comment]
Related https://github.com/gcanti/fp-ts-routing/issues/50

**Comment by merisbahti** [comment]
I see that I, myself, have answered my own question. But I still find that pattern kind of annoying or boilerplatey. I find that optional query-parameters are more common than non-optional ones. That's why I'm not suggesting having both `query` and `queryPartial`.

**Comment by gcanti** [comment]
LOL I didn't notice you were the author, sorry.

If we change the `query` signature to

```ts
export function query<A>(type: Type<A, Record<string, QueryValues>>): Match<A> {
  return new Match(
    new Parser(r => option.map(fromEither(type.decode(r.query)), query => tuple(query, new Route(r.parts, {})))),
    new Formatter((r, query) => new Route(r.parts, type.encode(query)))
  )
}
```

we can handle all codecs

```ts
const a = query(t.type({ a: t.string })) // ok
const b = query(t.strict({ a: t.string })) // ok
const c = query(t.partial({ b: t.string })) // ok
const d = query(t.intersection([t.type({ a: t.string }), t.partial({ b: t.string })])) // ok
```

There's a problem though, in case of an intersection you are allowed to pass invalid codecs

```ts
//                                                           number?? --v
const e = query(t.intersection([t.type({ a: t.string }), t.partial({ b: t.number })])) // no error!
```

Unfortunately that's how typescript works

```ts
type A = Record<string, string>
type B = { a: string } & { b: number }
declare const x: B
const y: A = x // no error!
```
