### ISSUE TITLE
query of inner page overwrite previous query

### ISSUE THREAD

**Issue by scink** [gcanti/fp-ts-routing#56]
hi.
i have a route, were i have date range in the query. then there is an inner page, that has sorting parameters. i use format function with match of inner page and all the query params and get path with query of inner page only.
i do not hope i succeed in explaining, so i'll try with some code

```
import {format, lit, query, str} from 'fp-ts-routing';
import {strict, string, undefined as undef, union} from 'io-ts';

describe('fp-ts-routing', () => {
	describe('format', () => {
		const q = strict({param: union([string, undef])});
		const q2 = strict({param2: union([string, undef])});

		const id = str('id');
		const page = id.then(lit('page').then(query(q)));
		const nextPage = page.then(lit('next')).then(query(q2));

		it('should be truthy for matching route', () => {
			const route = {
				id: 'some-id',
				param: 'some-param',
				param2: 'param2',
			};
			const path = '/some-id/page/next?param=some-param&param2=param2';

			expect(format(nextPage.formatter, route, true)).toEqual(path); // "/some-id/page/next?param2=param2"
		});
	});
});
```
the result:
<img width="450" alt="Screenshot 2021-01-29 at 16 33 36" src="https://user-images.githubusercontent.com/15276485/106281060-c27f6780-624f-11eb-8f75-5fb424352112.png">

i tried to use intersection like
```
const q = strict({param: union([string, undef])});
const q2 = strict({param2: union([string, undef])});
const q3 = intersection([q, q2]);
```
but i got a type error
<img width="1033" alt="Screenshot 2021-01-29 at 16 35 22" src="https://user-images.githubusercontent.com/15276485/106281233-ffe3f500-624f-11eb-8dfc-4140c93f2d8b.png">

do i do something wrong? or there is a problem in the library? if so, what can be done? except rewriting query for each page, of course :)

thanks

**Comment by gcanti** [comment]
@scink IIRC `query` is supposed to be used as a terminal element

**Comment by scink** [comment]
@gcanti, i see.
you gave me an idea:
```
describe('fp-ts-routing', () => {
	describe('format', () => {
		const q = strict({param: union([string, undef])});
		const q2 = strict({param2: union([string, undef])});
		const q3 = intersection([q, q2]);

		const id = str('id');
		const _page = id.then(lit('page'));
		const page = _page.then(query(q));
		const nextPage = _page.then(lit('next')).then(query(q3));

		it('should be truthy for matching route', () => {
			const route = {
				id: 'some-id',
				param: 'some-param',
				param2: 'param2',
			};
			const path = '/some-id/page/next?param=some-param&param2=param2';

			expect(format(nextPage.formatter, route, true)).toEqual(path); // works as expected
		});
	});
});
```
looks like crutch, but it works as expected. what do you think?

**Comment by gcanti** [comment]
:+1:
