### ISSUE TITLE
query fail with array

### ISSUE THREAD

**Issue by siuvdlec** [gcanti/fp-ts-routing#60]
I have created a small [example](https://stackblitz.com/edit/typescript-pd7xx4?file=index.ts) or you can check this [test](https://github.com/siuvdlec/fp-ts-routing/commit/60f06a7fbe7a146bc289ff3fab1c90155d82a3d8)

Maybe it could be a solution to replace `url` and `querystring` with [qs](https://www.npmjs.com/package/qs), this also fix the dependency issue for browser bundles

**Comment by StefanoMagrassi** [comment]
@siuvdlec with #70 we removed the `querystring` and `url` dependencies using the standard web API `URL` and `URLSearchParams`

The example you add in your test is not a standard syntax for query parameters: if you need something like that, you should define a special codec which can handle multiple parameters.

You can find an example in the test suite (just added via #71)
