### ISSUE TITLE
Pipeable methods for parsers and formatters

### ISSUE THREAD

**Issue by OliverJAsh** [gcanti/fp-ts-routing#63]
At the moment there is only one exported `then` function which works on `Match`, however I think we also need versions to cover `Parser` and `Formatter` (to replace the corresponding methods on those types).

Perhaps we could have separate modules for `Parser`, `Formatter` and `Match`. WDYT @gcanti?

**Comment by StefanoMagrassi** [comment]
@OliverJAsh with the current situation (only a `index.ts` file) we would the problem of names clashing.

Thus, maybe we could separate the source code in different modules and then add the pipeable version of those methods.

It shouldn't be an expensive task, but I think that we have to do some "chores" on the project (upgrade dependencies, remove tslint and so on...)
