### ISSUE TITLE
TypeScript 2.9.2: type errors related to keyof changes

### ISSUE THREAD

**Issue by hoodunit** [gcanti/fp-ts-routing#8]
On TypeScript 2.9.2 you see the following errors:

```
> typings-checker --allow-expect-error --project typings-checker/tsconfig.json typings-checker/index.ts

typings-checker/index.ts:20: Unexpected error
  A type predicate's type must be assignable to its parameter's type.
  Type 'A' is not assignable to type 'mixed'.
    Type 'A' is not assignable to type 'object'.

typings-checker/index.ts:70: Unexpected error
  Type 'keyof A' does not satisfy the constraint 'string'.
  Type 'string | number | symbol' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.

typings-checker/index.ts:89: Unexpected error
  Type 'keyof A' does not satisfy the constraint 'string'.
  Type 'string | number | symbol' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.

typings-checker/index.ts:100: Unexpected error
  Type 'keyof A' does not satisfy the constraint 'string'.
  Type 'string | number | symbol' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.

typings-checker/index.ts: 1 / 5 checks passed.
```

The first seems to be fixed by bumping io-ts versions. The others can be removed by changing `keyof A` to `Extract<string, keyof A>` in various places, but it seems to break this type check and I'm not sure why:

```
typings-checker/index.ts:5: Expected error Argument of type 'Match<{ a: string; }>' is not assignable to parameter of type 'Match<{ a: string; }> & Match<RowLacks<"a", { a: string; }>>'
```

**Comment by gcanti** [comment]
Thanks for the bug report

> The first seems to be fixed by bumping io-ts versions

Right, the first 2.9.x-compatible version of io-ts is `1.1.4`

> The others can be removed by changing keyof A to Extract<string, keyof A> in various places

Looks like the issue comes from `keyof` which is now returning `string | number | symbol`. Changing the `RowLacks` implementation seems to fix the problem.
Could you please try [my proposed fix](https://github.com/gcanti/fp-ts-routing/pull/9) on your codebase?

**Comment by hoodunit** [comment]
Installed in my project as "https://github.com/gcanti/fp-ts-routing/tarball/c9b12950500d6fba1d286c8ad204a74bf839837e" and I get this when I compile:
```
node_modules/fp-ts-routing/src/index.ts:29:29 - error TS2345: Argument of type 'string | ParsedUrlQuery | null | undefined' is not assignable to parameter of type 'Query'.
  Type 'undefined' is not assignable to type 'Query'.

29     return new Route(parts, route.query)
```

**Comment by gcanti** [comment]
which version of `@types/node` are you using?

**Comment by hoodunit** [comment]
9.4.6

**Comment by gcanti** [comment]
Ok, that's it. `url.parse` typings has changed (for the better). Pushed a fix

**Comment by hoodunit** [comment]
That compiles fine for me, but maybe it would be better to jump to the latest @types/node@10.3.3? I tried that and I get this error:
```
node_modules/fp-ts-routing/src/index.ts:29:29 - error TS2345: Argument of type 'ParsedUrlQuery' is not assignable to parameter of type 'Query'.
  Index signatures are incompatible.
    Type 'string | string[] | undefined' is not assignable to type 'string | string[]'.
      Type 'undefined' is not assignable to type 'string | string[]'.

29     return new Route(parts, route.query)
```

**Comment by gcanti** [comment]
> maybe it would be better to jump to the latest @10.3.3

ok, let me try...

**Comment by gcanti** [comment]
That's weird, `ParsedUrlQuery` has changed to 

```ts
interface ParsedUrlQuery { [key: string]: string | string[] | undefined; }
```

Not sure why they added `undefined` (is it even possible?)

**Comment by hoodunit** [comment]
[Your latest changes](https://github.com/gcanti/fp-ts-routing/pull/9/commits/bdb72fc80273af45f6e22142c1a384b5db7c04a8) compile for me and don't seem to break any of my (not very complicated) usage at run time.

**Comment by hoodunit** [comment]
Thanks!
